headerfs/store.go
Earlier `nil` was always returned, even on error, which could lead to `nil` pointer dereferencing here: https://github.com/lightninglabs/neutrino/blob/master/blockmanager.go#L293
=> BlockHeaderStore: return error when chainTip fails

blockmanager.go, blocksubscriptions.go, neutrino.go, rescan.go, sync_test.go
This pull request makes `go test -v .` work in the presence of updated `btcd` and reduces flake incidence in `lnd`'s `chainntfns` interface tests for `neutrino`. It does so via the following:
* Makes block notifications fully asynchronous
* Compensates for instances caused by the above where a rescan tries to read a block header after it's been reorganized out (improved handling of this will be added when the block subscription mechanism is factored out into its own package and message types abstracted out so they can be used in a single notification channel)
* Improves test robustness and error reporting
* Ensures `inv` messages are sent on connect if a peer reports that it has a longer chain than the chain service knows about
=> Reorg and notification fixes

rescan.go
In order to support key birthdays, rescans will now support a start time. If the start block is earlier than the start time, filters will not be downloaded and checked before the start time. `OnBlockConnected` and empty `OnFilteredBlockConnected` notifications are still sent prior to the start time, as are the block disconnected notifications.
In addition, the rescan's error channel is now buffered to prevent the rescan goroutine from being unable to exit, previously caused by the error channel not being read.
=> Add support for rescan start time

rescan.go
This PR adds a new functional `UpdateOption` that disables `OnBlockDisconnected` and `OnFilteredBlockDisconnected` notifications when rewinding a rescan. This will be used to make client implementation easier in `lnd` and therefore should be available to all clients.
=> rescan: add `DisableDisconnectedNtfns` update option for rewind

headerfs/store.go, neutrino.go, sync_test.go
This PR adds a test that triggers rapid, small reorgs which cause a panic in `neutrino` and sometimes also in `rpctest`.
The PR then adds a commit which ensures cfheaders are only rolled back if they're caught up to the height of the block being rolled back. This fixes a race condition which happens when a `headers` message with a reorg is processed before all of the `cfheaders` messages for currently-known blocks, triggering a panic on EOF from one of the filter header stores.
The PR also adds a commit which ensures that the block header store's `ChainTip` method is atomic, which prevents a race condition causing a panic on EOF from the block header store which is triggered when the database block index is written but the header file is not.
The `rpctest` issue will be resolved in a …
=> Fix panic caused by rapid small reorgs

headerfs/file.go, headerfs/store.go, headerfs/truncate.go, headerfs/truncate_windows.go
This PR fixes #21 on Windows. In addition, it fixes some linter errors in `store.go` and ensures that the header store flat files are created/opened without execute permissions.
=> Windows rollback fix

neutrino.go, notifications.go
This PR makes `addStringToNetAddr` a method on `ChainService`. This allows the function to now have access to the service's `ChainParams()` method, which allows it to default to a port if the address passed doesn't specify a port.
=> ChainService: use default port in `addStringToNetAddr` when not specified

headerfs/index.go, headerfs/store.go, rescan.go
This PR refactors locking in `headerfs` by making the `RWMutex` private and using it in all access methods to prevent certain race conditions and deadlocks. It also fixes a couple of small linter complaints in `headerfs/index.go`.
The PR also fixes a rescan race condition that happens when a rescan is notified of a new block but that block is reorged out while the rescan is attempting to fetch the filters for the block in order to match it.
This PR should address #25 and #26, as well as additional test failures/flakes.
=> Refactor locking in `headerfs`, fix rescan race condition during reorg

query.go
This PR prevents further processing in the CFilter callback when the `extended` flag doesn't match between the `getcfilter` command and the `cfilter` response, possibly due to another process requesting a cfilter of a different type for the same block.
In addition, the PR ensures that a valid filter or block received in a message notification callback is assigned to the original caller's result variable before the quit channel is closed. This should prevent `queryPeers()` from exiting before the variable is assigned and erroneously returning/trying to write a nil filter or block that actually matched.
=> query: race condition and performance fixes

blockmanager.go, rescan.go, sync_test.go
This PR:
- Fixes the notification order, making `OnBlockConnected` trigger after `OnFilteredBlockConnected` in order to comply with the way `btcwallet` expects the notifications
- reduces the severity of the `waiting for more` log message and makes the message text clearer in the cfheaders download code
=> Small fixes

rescan.go
This PR should fix the panic seen in https://github.com/lightninglabs/lightning-app/issues/87 by returning an error when a transaction which creates the requested output isn't created since the `StartBlock` argument to `GetUTXO`.
=> rescan: return error when `GetUTXO` outpoint not created since start block

rescan.go
Fix a panic I noticed during a shutdown of neutrino. The fix was to move handle the error from `ChainTip` in `GetUtxo` immediately before accessing any of the returned header's methods.
=> rescan: handle err in GetUtxo to prevent shutdown panic

blockmanager.go, filterdb/db.go, headerfs/store.go, neutrino.go, query.go, sync_test.go
This commit updates `neutrino` to comply wtih the new BIP157 and BIP158 specifications for filter, header, and wire message formats. It does not yet take full advantage of all of the optimizations made possible by the new format, such as parallelizing cfheader download, requesting multiple cfilters at once, etc.
=> multi: comply with updated BIP157+158 specifications

glide.lock, glide.yaml, utxoscanner.go
I did a big no-no, and realized that this channel
close is not necessary since we already cache the
result.
=> utxoscanner: prevent send on close channel + update glide

rescan.go
In this PR,  we fix an existing bug that would prevent us from
actually re-fetching filter header that we missed either due to the peer
not responding, us fetching from the peer while it was mid-reorg, or the
peer simply not being synced yet. We also lower the retry interval to
force us to the best chain tip more aggressively.
We also add an additional level of defense to ensure that
we'll properly sync our rescan state to the current best chain tip.
Before this commit, if our retry timer failed to trigger, or we overrode
the timer with a newer block hash, then we should fail to properly
re-process all blocks before that last timer tick and our past rescan
chain tip. By setting current to false here, we'll now talk forwards in
the chain, catching up on any missed blocks in the process.
=> rescan: use proper chan for filter re-fetch retries, close rescan loop if blocks are missed

cache/cache.go, cache/cacheable_filter.go, cache/lru/lru.go, cache/lru/lru_test.go, neutrino.go, query.go, query_test.go
Resolves #65.
First attempt at the filter cache.
A few things:
- ended up writing a very basic LRU instead of including the lib I pointed out (though it would have been a very lightweight dependency...),
- parse the queryOptions twice to see if persistToDisk was set, seems ugly, but otherwise, it would be necessary to parse it in GetCFilter and change the `queryPeers` signature to take a final queryOption, but then all the callers of `queryPeers` will need to parse it too.
- regular and extended filters share the same cache, should they have different caches ?
- default cache size is 20.
=> Use lru cache for filters.

errors.go, rescan.go, utxoscanner.go, utxoscanner_test.go
This PR adds the ability to cancel GetUtxo
requests via two means:
* a configurable cancel channel
* automatically when shutting down the utxoscanner
The first is accomplished by selecting on an extra
cancel, which returns ErrGetUtxoCancelled if signaled
before the result has arrived.
The second iterates through all requests which have
been queued but not started, and cancels them all
with ErrGetUtxoCancelled. This should enable to
dependent systems to break out of long-running
queries, especially during shutdown.
=> utxoscanner: break get utxo

query.go, sync_test.go
- uses the mainline btcd APIs included in latest glide update
- uses `--txindex` on nodes in `sync_test.go`
- prevent queryBatch from stalling by removing for loop
=> Use btcd mainline APIs + prevent queryBatch from stalling

query.go
This commit fixes a known issue where that causes
the batch fetching to panic if the peer has been
removed from the peer set. If the peer is not
found, we initiate the cleanup logic as if the
peer were found, but no longer connected.
=> query: cleanup unknown peers, prevent nil panic

rescan.go, sync_test.go
This PR fixes an issue within the current `neutrino` rescan logic, which would cause a send on the `updateChan` to block indefinitely. 
This was caused by a caller of `Update` killing the current rescan at the same time, making the update never being read from the channel.
This PR fixes that by ensuring an error is returned if the rescan exits while the update is being enqueued, moving the responsibility to handle this case to the caller.
NOTE: The caller in this case is `btcwallet`, which must be updated to handle the returned error.
=> Fix rescan update deadlock

blockmanager.go
Previosly the header hash was used, which would be wrong if headers and
filter headers were out of sync, leading to weird behavior.
=> blockmanager: set filterHeaderTipHash to actual filter hash in Start

blockmanager.go
queryResponses was recently changed from being a slice to a map.
Previously a length check was performed to make sure we didn't index out
of bounds, but after the change to using a map this is no longer
correct.
This would be apparent doing header download from multiple peers, as
responses would come asynchronously, and the headers wouldn't be written
because of this check.
=> blockmanager: remove queryResponse length check

blockmanager.go, neutrino.go
Catch up filter headers and block headers in parallel. 
Also includes a fix for rollback of filter headers, and a proper fix to what was attempted in #95.
=> Catch up filter headers and block headers in parallel

blockmanager.go, neutrino.go, rescan.go, sync_test.go
This PR changes how the Neutrino `ChainService` is reporting the current best block. The best block known by the backend is now the minimum of the synced block headers and filter headers.
This fixes several issues seen, where the user of the ChainService would query for the best block, then attempt to use the chain from the reported height, even though Neutrino is not ready to handle queries before the filter headers are synced.
This also makes the `IsCurrent` API only report that we are current when filter headers are fully synced.
Builds on #98, #99 
Fixes #97
=> Make chain service API expose best block as min(block header, filter header)

rescan.go
This avoids a race condition where the rescan would mutate the header
while the block handlers where handling it.
Became apparent when running `lnd` compiled with `-race`.
=> rescan: let notifyBlock take copy of current header/stamp

blockmanager.go, blockmanager_test.go, headerfs/index.go, neutrino.go, query.go
Adds more information to the logs in an attempt to pinpoint #100.
Also adds a new test that ensures the blockmanager can handle responses out of order, and partially written filter header intervals.
=> Add more query batch logging

blockmanager.go
This commit fixes a nil pointer dereference that could happen for nets
having no checkpoints, where we would attempt to dereference the pointer
to a nil hash.
We fix this by not dereferenceing before the height has been checked.
Comments are updated to reflect the change.
=> blockmanager: avoid dereferencing nil checkpoint hash

blockmanager.go, blockmanager_test.go
This let us verify that the received interval matches up with the previous intervals, and that it is derived from the correct genesis. 
Earlier we would crash with an attempt of writing headers out of order in these cases.
Builds on #106 
Fixes #100
=> Handle misaligned intervals on sync

blockmanager.go
This PR is an attempt to reduce the time it takes for neutrino to sync on start.
It fixes a specific problem in the case where the current tip state has passed the last checkpoint therefore cfheaders queries of one of the checkpoints range is needed.
In that case we can skip the query call as when called with empty queries it just wait until timeout takes 3 seconds by default.
=> Remove unnecessary call to queryBatch in case of no queries.

blockmanager.go, blockmanager_test.go, neutrino.go
In this commit, we perform a small refactoring to pass in the
`firstPeerConnect` channel as an argument to the constructor of the
blockManager rather than passing it via the start method.
=> neutrino: pass firstPeerConnect as arg to blockManager constructor

blockmanager.go, neutrino.go
In this commit, we fix a bug in the way we attempt to verify the filters
during conflict resolution. A bug was fixed in the `btcutil` library
that would add some OP_RETURN items to the filter incorrectly. This was
remedied in the library, but this check was never updated itself. We put
all libraries in line by skipping _all_ OP_RETURN outputs when we
attempt to verify the integrity of a filter.
=> blockmanager: fix OP_RETURN bug

cache/cache_test.go, cache/cacheable_filter.go, query.go
Using a block hash pointer in the filter cache key would lead to the key
not being equal even when the block hash matched.
=> Cache key fix

blockntfns/manager.go, rescan.go
This is needed as otherwise we'd panic trying to send into the block subscription's closed notification channel since the subscription is canceled once we're not current.
Fixes #135.
=> rescan: reset block refetch timer in case we're not current 

blockmanager.go
We could fail writing the received headers since they didn't match up with what we had already.
=> Validate received PrevFilterHeader

blockmanager.go, neutrino.go, notifications.go, query.go
Split off from #129, needs some re-working of the unit tests in order to be merged. Right now the tests require an entire `ChainSerivce`, but the current test version isn't full populated so we get panics for the block manager filter reconciliation tests. 
In this commit, we also now will ban peers that advertise a checkpoint, but then deliver 
an incorrect filter header in that checkpoint range. This can also happen 
if new peers (with invalid state) join after we've verified the checkpoints 
of all our starting peers.
=> blockmanager: ban peers that equivocate on filter headers/checkpoints

blockmanager.go
If headers were written while lnd was in the process of shutting down it
would panic with a "Database not open" error.
=> blockmanager: remove panic on failed WriteHeaders

neutrino.go
If a peer that couldn't serve compact filters were part of our set of
permanent peers we would disconnect and re-connect over and over again.
To avoid this happening we make the connmgr remove the peer instead, and
we also ban it to avoid connecting to it again later.
=> peer handling: ban and remove non-filter peers

neutrino.go
We do this to ensure we don't have more than once active connection per peer. This is needed since the addrManager has no idea about the client's currently connected peers.
We also ensure we don't reconnect to banned peers -- there's no point in attempting to do so if we'll disconnect them anyway.
=> neutrino: reject address suggestions for already connected peers

cache/cache.go, cache/lru/lru.go, cache/lru/lru_test.go, headerfs/file.go, headerfs/index.go, headerfs/store.go, neutrino.go, query.go, rescan.go
This PR implements batch filter fetching. This is achieved by giving the callers of `GetCFilter` the option to make a "optimistic batch query", where the filters following the requested filters are also fetched, and added to the filter cache.
I ran this on mainnet to find cache size needed to keep a whole filter batch, and a size of 30 MB could hold at minimum 1483 elements (tested on filters at height > 515110), which should give us some wiggle room.
=> Batch filter fetching

go.mod, rescan.go, sync_test.go
In this commit, we address a bug that would prevent the wallet from starting until a new block arrives if it was one block behind the tip of the chain. This is due to an implicit order in the way the Neutrino ChainSource within btcwallet handles RescanProgress and RescanFinished notifications. A RescanFinished notification (dispatched by the OnFilteredBlockConnected callback) can only get triggered after a RescanProgress notification (dispatched by the OnBlockConnected callback), so we swap the order of the two notification callbacks to ensure it matches the expected behavior.
=> rescan: dispatch OnBlockConnected before OnFilteredBlockConnected

pushtx/broadcaster.go, pushtx/broadcaster_test.go
This commit makes the rebroadcast logic being run in a goroutine. This
is done to ensure we don't block the whole broadcast loop while
performing a rebroadcast.
Rebroadcasts can be slow if the number of transactions are large (each
broadcast has a timeout of 0.5s), which would cause publishing new
transactions to block. With this commit we let the rebroadcast continue
in the background, while we can keep pushing new txs.
=> pushtx/broadcaster: make rebroadcast tx async

bamboozle_unit_test.go, blockmanager_test.go, headerfs/file.go, headerfs/store.go, headerfs/store_test.go, neutrino.go
In this commit, we add the ability to specify an expected filter header
state when the filter header store is being created. As the filter
headers aren't committed yet, it's at times useful to nudge existing
nodes towards a filter header chain that they themselves may not have
obtained previously.
=> headerfs: add ability to assert the state of the filter header chain

go.mod, headerfs/store.go, headerfs/store_test.go
This is necessary as otherwise the filter header store would maintain the removed invalid filter header state in memory, causing us to still query for it.
=> headerfs: re-initialize filter header store after removal

go.mod, go.sum
Updating to this version ensures that ComputePkScript can handle P2PKH
signature scripts with variable signature lengths.
=> build: update to latest btcd dependency with ComputePkScript fix

pushtx/broadcaster.go
It would log on every block, which during initial sync would fill the
logs.
=> pushtx: demote existing rebroadcast log to trace

blockmanager.go
There was a previous assumption that filterHeaderTip and filterHeaderTipHash were only being accessed within the cfHandler goroutine. This is no longer the case, as we require the filter header
tip in order to deliver a backlog of notifications for block notification subscribers.
We also establish a locking order when needing to acquire both newHeadersMtx and newFilterHeadersMtx in certain cases.
This attempts to address a deadlock found in this [goroutine dump](https://pastebin.com/raw/ZqbQKjpH).
=> blockmanager: address filter header tip lock inconsistency 

bamboozle_unit_test.go, blockmanager.go, blockmanager_test.go, mock_store.go, query.go
This PR adds a set of extra consistency checks to downloaded filters, in an attempt to ban peers that are serving either old filter types, or filters that are inconsistent with the filter headers.
If we cannot determine directly from the filter headers that a peer is serving invalid filters we employ the following strategies in attempt to ban the smallest set of peers needed for the sync not to stall:
1. If a peers' filter doesn't match on a script that must match, we know the filter is invalid.
2. If a peers' filter matches on a script that _should not_ match, it is potentially invalid. In this case we ban peers that matches more such scripts than other peers.
3. If we cannot detect which filters are invalid from the block contents, we ban peers serving filters different from the …
=> Detect peers serving invalid filters

blockmanager.go, chainsync/filtercontrol.go, chainsync/filtercontrol_test.go
Before starting to compare filter checkpoints our peers are serving, we
do a quick check against a list of filter header checkpoints we have.
Note that this PR doesn't actually add the checkpoints, these should be cross checked from different nodes.
=> Check filter header checkpoints against hardcoded list

banman/codec.go, banman/codec_test.go, banman/reason.go, banman/store.go, banman/store_test.go, banman/util.go, banman/util_test.go, blockmanager.go, blockmanager_test.go, neutrino.go, notifications.go, sync_test.go
In this PR, we introduce a new BanStore interface, along with a concrete implementation that will be backed by a boltdb instance, that will serve as a persistent ban store for peers. This prevents us from reconnecting to known bad peers until their respective ban expires.
=>  banman: add BanStore interface with implementation

banman/store.go, chainsync/filtercontrol.go
In this PR, we add known to be valid filter header checkpoint hashes
for mainnet and testnet. These simply allow peers to avoid downloading
invalid filters and banning peers which we already know are running
incorrect versions of the software. For all blocks past this point,
we'll rely on our normal validation to tend towards the correct filter
header chain.
=> chainsync: populate testnet+mainnet filter header meta checkpoints

neutrino.go
In order to be able to bootstrap a new node w/o having to manually use a
`connect` or `addpeer`, we'll now assume the returned addresses have the
proper service bits implicitly. Since the seeds return just A records,
unless we pack things into IPv6, they can't explicitly signal the
service bits they support. Many of the DNS seeds were recently upgraded
to be able to respond to the `x49` subdomain (full node, segwit, bip
158), so with this change, usersr can now bootstrap a new node w/o any
externally obtained addresses.
Note that with this approach, if they peer actually supports of subset
of the features we need, they'll be lost. However, As we grow to
eventually need these additional services, the RequiredServices constant
will be updated, allowing us to filter based on these new …
=> neutrino: manually apply service bits to DNS seed addrs

blockmanager.go, blockmanager_test.go
In this commit, we make a simple optimization to the process of retrieving checkpointed cfheaders by reducing the amount of round trips by half. This is done by requesting MaxCFHeadersMsg (2000) filter headers per query instead of CFCheckptInterval (1000).
=> blockmanager: fetch MaxCFHeadersPerMsg for checkpointed cfheaders

neutrino.go
Manually disconnect the peer even though BanPeer attempts to do so because it has yet to be added.
=> neutrino: manually disconnect peers not serving cfilters

neutrino.go, query.go, rescan.go, rescan_test.go
In this commit, we address a lingering issue within the Rescan struct where it was possible for it to deliver notifications out of order. This was due to the fact that retrying block filter fetches replaced attempts for previous blocks, causing us to move forward without dispatching notifications for those previous blocks. We'll now continue to retry fetching a block filter until successful or stale, and new blocks that come in while doing so will be stashed and retried later on in the order that they arrived.
Along the way, to ensure the correctness of this behavior, a test harness was created to aid testing. The test harness accounts for most of the diff in this PR.
Fixes https://github.com/lightninglabs/neutrino/issues/166.
=> rescan: stash blocks to retry after filter fetch failure

.travis.yml, go.sum, query.go, rescan.go, rescan_test.go
Previously we would return a nil filter with nil error, which would mask
a failed filter fetch.
=> Return error on failed CFilter queries

neutrino.go
This is a port from the same set of fixes applied to `btcd` in https://github.com/btcsuite/btcd/pull/1480.
=> neutrino: refactor OnVersion to instead add peers within OnVerAck

neutrino.go
Doing so would get us in a loop where we continue to request connections but we end up disconnecting them due to already having our maximum number of peers.
=> neutrino: don't request new connections once max peers is reached

batch_spend_reporter.go, rescan.go, utxoscanner.go, utxoscanner_test.go
This PR suggests to add progress notifications to the utxo scanning process.
Currently the caller only gets feedback at the end of the process where it can be sometimes very long.
Besides the feedback there is a need to be able to start the scanning from the last point it has stopped. This is achieved in LND, for example, by using a "SpendHint" cache but it only updates the cache at the end of the process which creates a problem for mobile users that don't open their app for several weeks. The utxo scanning at this case is likely to be longer than the time their app will be online resulting in scanning all over again on every restart.
This addition will enable LND to update the hint cache during the scanning progress resulting in better incremental rescan between restarts.
=> neutrino: support utxo scanner progress.

headerfs/index.go, headerfs/index_test.go, headerfs/store.go, headerfs/store_test.go
Fixes https://github.com/lightninglabs/neutrino/issues/196.
With this PR we store the block index keys (hash->height) in sub-
buckets with the first two bytes of the hash as the bucket name.
Storing a large number of keys in the same bucket has a large
impact on memory usage in bbolt if small-ish batch sizes are
used (the b+ tree needs to be copied with every resize operation).
Using sub buckets is a compromise between memory usage and
access time. 2 bytes (=max 65535 sub buckets) seems to be the
sweet spot (-50% memory usage, +30% access time). We take the
bytes from the beginning of the byte-serialized hash since all
Bitcoin hashes are reverse-serialized when displayed as
strings. That means the leading zeroes of a block hash
are actually at the end of the byte slice.
As the benchmarks …
=> Fix memory usage of bbolt block header index

batch_spend_reporter.go, rescan.go, sync_test.go
That modifies the `SpendReport` struct to add fields for `BlockHash`, `BlockHeight`, and `BlockIndex` for unspent outputs. The data was already available, just not being recorded.
=> add block info to SpendReport for unspent outputs

blockmanager.go, chainsync/filtercontrol.go, go.mod, neutrino.go, rescan.go, verification.go, verification_test.go
Fixes https://github.com/lightninglabs/neutrino/issues/207.
Whenever we download a block, we want to make sure that the filter we
had for it was correct. It's trivial to check all output scripts of the
block's transactions were included in the filter. The trickier part is
to verify the scripts of the outputs being spent are also included in
the filter.
By looking at the signature script or witness we can derive the script
that's being spent and from that can make sure they are all included in
the filter.
=> Validate received filters after block download, update filter checkpoints

utxoscanner.go
On startup, noticed that if there are a lot of `filterEntries` leads to high mem usage, they all get copied here:
```
options = &rescanOptions{
watchList: reporter.filterEntries,
}
```
and they continually get copied until a match is found. With pprof, noticed about 38MB, sometimes more depending on the `channel.db` I was using:
```
38.01MB    38.01MB    321:			options := rescanOptions{
.          .    322:				watchList: reporter.filterEntries,
.          .    323:			}
```
With this change, pprof doesn't even log the memory since it's so low. :) 
EDIT: I know that with batching filter requests, this probably isn't necessary, but for now it's a nice memory improvement.
=> utxoscanner: reuse options where possible

query.go
The current time of 500ms can be too low if for example the network conditions are poor.
This increases the timeout window to 10s which should be sufficient to cover any scenarios.
This has been causing real issues with lnd (and bitcoind) where `SendCoins` and channel openings wouldn't get broadcasted.
https://github.com/lightningnetwork/lnd/issues/5130
https://github.com/hsjoberg/blixt-wallet/issues/278
@wpaulino I've removed your TODO-message which was directly related to this issue, if that's okay with you.
Cheers!
=> neutrino: increase timeout between inv and getmsg when sending tx 

neutrino.go, query.go
Fix #193 
Currently PersisToDisk is an option to GetCFilter.
The problem is that the option is not working well with the in-memory
FilterCache. The biggest problem is that if there are two calls of
GetCFilter, the first one without the PersistToDisk option, and the second
one with the PersistToDisk option, the second one returns the filter from
the cache and doesn't write it persistently to the disk.
Consequently, if a filter was already queried, there is no way to write it
to disk. So for instance if a neutrino user (mainly lnd) is closed before
it is fully synchronized, it need to re-download all the filters when it
runs again.
When handling the PersistToDisk in the ChainService itself, the caller of
NewChainService decides in _one place_ if the filters need to be stored
in the disk, …
=> Add PersistToDisk property to ChainService

neutrino.go, pushtx/broadcaster.go, query.go
This is useful for enabling shorter timeouts than we would use in a production environment in testing environments, resulting in shorter test execution times. If a timeout isn't provided, we'll use the default of 5 seconds.
=> neutrino+pushtx: make broadcast timeout configurable with fallback

.github/workflows/main.yml, Makefile
I should have tested the new GH actions of previously merged PR...
Now verified both locally with `act` and [on my fork](https://github.com/guggero/neutrino/actions/runs/816859251) that the fixes work.
=> Fix GitHub actions

pushtx/broadcaster.go, pushtx/broadcaster_test.go, rescan.go
This PR allows rescan to notify the `ChainServices` `broadcaster` that a relevant transaction is confirmed.
Fixes #206  using the approach mentioned [here](https://github.com/lightninglabs/neutrino/issues/206#issuecomment-887919095)
**Testing the PR**
- _To see the bug_: An easy way to test this just by running an lnd itest that creates some channels and then observing the logs. So currently, if you run `$ make itest backend=neutrino icase=....` (choose a test that creates a lot of channels) and then look at the logs: `[DBG] BTCN: Re-broadcasting %d transactions`  will show that the number of txs being rebroadcasted just keeps increasing. 
- _To see the fix:_ now in lnd go.mod, add: `replace github.com/lightninglabs/neutrino => github.com/ellemouton/neutrino …
=> pushtx+rescan: stop rebroadcast on tx confirm

verification.go, verification_test.go
In this commit, the checks for input script pub keys is removed since the function used to reconstruct script pub keys from witness data currently does not take taproot outputs into consideration and so is producing the wrong script pubkeys which then causes the verification to fail. This code can be put back once the ComputeScriptPubKey function takes taproot into account. 
off the top of my head, I think that the ComputeScriptPubKey function might need to be changed to return a set of options since i think sometimes we wont be able to tell the difference between a P2WPKH, P2TR key path with annex, P2TR script path.
=> verification: skip checking input scripts

blockmanager.go, headerfs/store.go, neutrino.go, rescan.go
The `headerfs.BlockStamp` returned from `(*ChainService).BestBlock` had a zero `Timestamp`.
This change sets the `Timestamp` field from the block header if available.
Internally it does not seem to matter that `Timestamp` is the zero `time.Time`, but for `ChainService` consumers it is helpful to have the block's timestamp.  For example, one may compare the timestamp from the current best block from `ChainService` to the wallet `Manager`'s birthday time.
=> set headerfs.BlockStamp.Timestamp

query.go, sync_test.go
`(*ChainService).sendTransaction`  always times out even if each peer does respond.  This is because after receiving a `getdata` message in response to the outgoing `inv`, the `checkResponse` closure provided to `queryAllPeers` neglects to close the `peerQuit` channel.  As a result, `sendTransaction` always blocks for the full configured `BroadcastTimeout`.
This change adds the missing `close(peerQuit)` when a matching response (either a getdata or reject) is received.  I have tested this fix in our app, and sends no longer always time out when all peers respond with a getdata.
This change also makes a note in the `sendTransaction` function that the `if numReplied == len(rejections) {` test at the end is currently impossible to hit since `numReplied` would also need to be incremented when …
=> query: end completed queries in sendTransaction before timeout

README.md
Fixes #225.
In the above issue we mentioned that we'd drop those warnings after the latest release ([`v0.13.0`](https://github.com/lightninglabs/neutrino/releases/tag/v0.13.0)) so I assume we're comfortable with not warning against using on mainnet anymore.
=> Update README to remove experimental and mainnet usage warnings

blockmanager_test.go, neutrino.go
These functions need to public to be able to add peers to an existing ChainService.
=> Export newPeerConfig and newServerPeer

.gitignore, cache/lru/lru.go, cache/lru/lru_test.go, cache/lru/sync_map.go
This commit adds three methods, `Delete`, `LoadAndDelete`, and `Range` to the lru cache.
=> cache: add deletion and iteration methods

verification.go
We can't re-create the pkScript from a keyspend p2tr witness, as we're missing the public key. So this warning will trigger for each block that contains a p2tr key spend, which isn't really useful and confuses users. So we're downgrading the error to a debug message.
=> verification: mute taproot related err to dbg

chanutils/batch_writer.go, chanutils/batch_writer_test.go, chanutils/log.go, chanutils/queue.go, filterdb/db.go, filterdb/db_test.go, filterdb/log.go, log.go, neutrino.go, query.go
This PR adds a generic `BatchWriter` which can be used to batch write items to a db.
It persists the batch once the size reaches a certain threshold _or_ if a ticker goes off 
if at least one items is in the batch. 
This `BatchWriter` is then used by the `GetCFilter` method to persist filters that it
gets during a query. This will improve the speed of the query since the `BatchWriter` is
non-blocking. 
On current master branch, syncing 3200 filters on my local regtest network takes 4m25s
With this PR, syncing the same number of filters takes 4.2s
LND CI with this PR is being tested here: https://github.com/lightningnetwork/lnd/pull/7788
=> multi: introduce a batch filter writer

rescan.go, rescan_test.go
With this PR, we ensure that `rescan` can make use of batch filter fetching by 
waiting until the header chain is either current or until it is ahead of the specified 
end height before starting the scan. This greatly improves the speed of a rescan 
because before this commit, the filters would be fetched one-by-one. 
The first few commits of this PR are just refactor commits that clean-up the `rescan`
function and then the actual behaviour change is added in the final commit. 
Fixes https://github.com/lightninglabs/neutrino/issues/68
Replaces https://github.com/lightninglabs/neutrino/pull/236
On current master branch, syncing 3200 filters on my local regtest network takes 4m25s
With this PR, syncing the same number of filters takes 653ms
https://github.com/lightningnetwork/lnd/pull/7788
=> rescan: use batch filter fetching

query/peer_rank.go, query/peer_rank_test.go, query/workmanager.go, query/workmanager_test.go
This PR addresses https://github.com/lightninglabs/neutrino/issues/280
Fixes #280
=> neutrino: Added ResetRanking method to PeerRanking.

query/worker.go, query/workmanager.go, query/workmanager_test.go
Fixes https://github.com/lightningnetwork/lnd/issues/8593
In general I will rework this code area in LND 19 because this needs an overhaul and relates to https://github.com/btcsuite/btcwallet/issues/904 
In the current code there is an edge case which manifests itself when the used backend has very unstable connections and also not a lot of outbound peers which results in queryJobs waiting a long time in the queue. Then we would timeout the batch here:
https://github.com/lightninglabs/neutrino/blob/43f5a588eb4a53cb36d118420e186629154086da/query/workmanager.go#L420-L433
but the queryJob was already registered for a second try here:
https://github.com/lightninglabs/neutrino/blob/43f5a588eb4a53cb36d118420e186629154086da/query/workmanager.go#L388-L389
Now this query will be tried all over …
=> query: fix retry query case.

banman/store.go, banman/store_test.go, neutrino.go
Changes:
- Added unbanpeer method to chainservice.
- Added unbanipnet method to banstore
Link to issue: https://github.com/lightninglabs/neutrino/issues/253
Link to previous PR for context:
https://github.com/lightninglabs/neutrino/pull/270/
=> Added unban peer feature

neutrino.go, query.go, rescan.go
After working with @hsjoberg and @niteshbalusu11 to troubleshoot Blixt performance we realized two things were consistently going wrong in networks with > around 300ms latency:
1. Retries would be exhausted quickly
2. Due to that --^ timeouts being doubled did not help much
After investigating, we decided to experiment with changing some constants in neutrino to work better.
This PR addresses both issues by:
- Decreasing maxBatch to 10
- Increasing query retries from 2 to 8
- Increasing rescan retries from 1 to 2
- Increasing broadcast query retries from 1 to 8
The result is that we can now use Blixt with networks that we could not previously.
=> neutrino: improve perf in high latency networks

headerfs/index.go
Adds an error message when there is a missing key (happens if neutrino.db is deleted for example).
=> Headerfs: add error msg

verification.go
There was a missing space between words:
"The input likely spends a taproot output which is not yetsupported"
=> verification: fix log line
