- rescan.go
This fixes a few bugs that I believe are causing flaky tests on lnd. Some of the bugs are:
1. If an update is applied at the wrong time and hits the second statement handling updates, the block notification for the first block after the rewind would not get sent. Basically, if it hit the update filter clause at the end of the loop instead of the one when `current = true` it would restart at the top of the loop and fetch the next block.
2. If rewinds were applied, multiple subscriptions would be made and only one would be unsubscribed at the end. Now we unsubscribe ever time current is set to false. Furthermore, passing `ro.quit` into the subscription created a race where there were multiple consumers of that channel.
3. We need to wait for both the basic filter and extended filter before …
> rescan: Refactor main loop and fix a few bugs/race conditions.

- .travis.yml
- blockmanager.go
- glide.lock
- glide.yaml
- gotest.sh
- headerfs/store_test.go
- neutrino.go
- notifications.go
- query.go
This PR adds a test script (`gotest.sh`) and a `.travis.yml` file shamelessly stolen from `lnd` and slightly modified to remove currently-unused features. It requires Travis to be enabled for the repository. The removed features will be re-added as tests evolve to support them.
> build: enable Travis CI

- blockmanager.go
- filterdb/db.go
- filterdb/db_test.go
- glide.lock
- glide.yaml
- headerfs/store.go
- neutrino.go
- query.go
- rescan.go
- sync_test.go
This PR updates the `neutrino` code to be able to correctly use the `btcd` code updated to comply with the cfilter BIP.
> multi: update to BIP-compliant btcd

- neutrino.go
In this commit, we add two new arguments to the Config struct that will
allow a caller to specify their own custom dialer along with name
resolver. With this setup, callers will be able to proxy *all* traffic
as they wish. The primary motivation for this change is to add support
for Tor over a SOCKS proxy.
Partially fixes #10.
> allow specification of a custom dialer and name resolver 

- .gitignore
- filterdb/db.go
fix a typo and add .idea to .gitignore
> fix a typo and add .idea to .gitignore

- blockmanager.go
- headerfs/index.go
- headerfs/store.go
- rescan.go
The changes are scoped to fixed spelling mistakes within comments only 
My first day using GIThub, apologies if this is submitted in an unexpected manner!
> Fix spelling mistakes in comments in neutrino 

- rescan.go
In this commit, we update neutrino to match a recent change to the BIP
itself. Rather than looking for the push datas in a script, we'll
actually instead just look for the script itself. This is due to the
fact that we'll now index the entire script rather then each individual
push.
> rescan: match against the raw script for an addr, not its datapush

- rescan.go
This reverts commit e77fa7d999e8d41241e00ca77a57f4100d9cd4f9.
It turned out that without this check we risk trying to process blocks that are already re-orged out, and hence the filter header deleted, causing tests to be flaky. 
Might not be the best way to handle this case, but reverting for now to get tests running.
> Revert "rescan: remove filter header check on connected block"

- blockmanager.go
- neutrino.go
This PR is a suggested way to reduce about 3 seconds (with default configuration) from neutrino startup time on some cases.
From within BlockManager the function cfHandler is called right on start regardless if there is at least one peer connected.
Since this function query the peers it causes the first query to fail with high probability and retry after a waiting period of QueryTimeout interval (3 seconds by default).
I have tested the startup on mobile devices and found that the first peer connection is usually established in less than 1 second, which creates a waste of 2-3 seconds.
My suggestion is to start the cfHandler after there is at least one peer, making sure the query has a target.
> Ensure at least one peer is connected before starting cfheader sync.

- query.go
NumRetries signals that we should retry all of our peers a certain amount of times. Before this commit, if set to 0, we'd skip over all of our remaining peers because peerTries would return a 0 value if the peer had yet to be tried. We fix this by ensuring that we try all peers _once_ regardless of what NumRetries is set to.
> query: query remaining peers when NumRetries is 0

- go.mod
- go.sum
The latest version of btcutil includes a bug fix for filter matching, as
well as an optimization for both filter construction and matching.
> build: update btcutil to latest version

- query.go
This commit adds a peer cooldown to the query logic. This is done to
avoid giving the same query immediately to the peer that timed out,
which could cause sync to stall on a bad peer.
> query: add peer cooldown

- query.go
We did not check whether the channel was actually sent on or closed,
which could cause us to believe the query was answered while in reality
the peer was about to shut down.
> query: handle closing matchSignal for peer query

- query.go
Doing so prevents us from waiting until the query's timeout is reached if we happened to receive the last response in order to satisfy all of our in-flight queries.
> query: exit if all queries are answered after receiving a response

- query.go
In this commit, we aim to fix an issue that can cause a query to fail
all together for a large query over a possibly high latency link. Before
this commit, we if attempted to query for several filters at once, on
mobile phones, it's possible that we timeout part way through. As is,
we'll then exit, and fail to properly retry, messing up the main rescan
loop.
In this commit, we aim to address this by _resetting_ the `peerTimeout`
each time we receive a message. Rather than aim to complete the entire
query in the timeout interval, we instead modify the timeout to ensure
forward progress of the query. If the peer isn't responding, then the
`peerTimeout` will tick, and we'll switch to another peer.
As a result, it's now possible that a query takes longer than
`QueryPeerConnectTimeout` if a …
> query: reset the main timeout each time a message is received

- query.go
This fixes an issue that could happen if a response to a previously
timed out query was received during sync. This could cause the response
handler to send on the peer's matchSignal, but the peerGoroutine was no
longer listening on the channel, causing sync to stall.
Instead we tie the matchSignal channel to the specific query, such that
we know that we only send the signal if the current query is
successfully handled, and we buffer the channel to ensure no blocking
even after a timeout.
> query: use per-query matchSignals.

- query.go
**The problem**
This PR follows https://github.com/lightninglabs/neutrino/pull/170 that has fixed the case where neutrino disconnects due to timeout during a batch request.
That PR fixed one aspect of the problem and as noted here https://github.com/lightninglabs/neutrino/pull/170#issuecomment-514043210, more tests have shown there is probably an additional mechanism that disconnects the remote peer.
Since neutrino is using the same peer.go file that btcd uses (https://github.com/btcsuite/btcd/blob/master/peer/peer.go) to handle peer communication it inherits also the staleHandler (https://github.com/btcsuite/btcd/blob/c26ffa870fd817666a857af1bf6498fabba1ffe3/peer/peer.go#L1174) that tracks every sent request and disconnects peers that don't send a response in some time limit (30 seconds …
> Wait for filters batch to complete before returning the requested filter.

- filterdb/db.go
This PR adds the ability to purge the filters from the db. Neutrino has the `PersistToDisk` query option which is useful for background sync in mobile applications. These apps can set a background job to fetch the filters periodically, preparing the data for the app when it starts by the user, which achieves a fast sync time and immediate readiness for payment.
This change adds a way to purge these filters and enables the app to implement its own eviction strategy preventing the db from growing boundlessly.
> filterdb: Implement PurgeFilters.

- query.go
This PR adds a query option `MaxBatchSize` that allows the caller to limit the batch size requested when using either `OptimisticBatch` or `OptimisticReverseBatch`.
This option is useful in cases where the caller needs a limited amount of items (such as scanning backwards to a certain point) and wants to allow neutrino save bandwidth by "hinting" about the max items it needs.
The term "maxBatchSize" is used rather than "batchSize" since the caller is not exposed to the max number of items neutrino used as a default and is only allowed to limit this number.
This change is the first step towards fixing https://github.com/lightningnetwork/lnd/issues/4060
> Add MaxBatchSize query option.

- neutrino.go
If network access was not yet established (e.g. on mobile device in
flight mode) the ChainService would fail to start since the IP address
of permanent peers could not be looked up.
We retry if this lookup fail, to allow the chain service to start.
Fixes https://github.com/lightningnetwork/lnd/issues/4016
> chainservice: retry lookup IP on startup

- neutrino.go
This PR allows a custom block cache to be passed to neutrino so that there can be a shared block cache between neutrino and whichever client may be using it. 
This diff is a step towards having an LND block cache (WIP is [here](https://github.com/ellemouton/lnd/pull/8))
> neutrino: allow custom block cache

- Makefile
Otherwise the test runs fails as no btcd binary is installed.
> build: add btcd installation to the new Makefile

- neutrino.go
This treats regnet like simnet with respect to node discovery and outbound connections.
Without this change, using regnet without `--connect`/`ConnectPeers` results in peer connection errors being logged ad nauseum.  e.g. tons of logs like `Failed to connect to reqid 78: no valid connect address`, eventually giving up.,
The workaround is to always use `ConnectPeers` on regnet, but peer discovery is really best disabled for regnet as well as simnet.
A similar change was made in dcrd in https://github.com/decred/dcrd/commit/f5fdd95eb578a485b414331836f9731fcd0f2756
Would like to test a bit more to be sure nothing unexpected happens on our regnet harness, so in draft for the moment.
> server: Actively prevent regnet network discovery

- query.go
This is a follow-up PR to fix an issue that https://github.com/lightninglabs/neutrino/pull/240 seems to have introduced.
When we close the `peerQuit` channel after receiving an INV message, we don't wait for any reject messages from that peer.
Instead we want to wait a bit longer after an INV message to make sure they don't respond with a reject message. Otherwise we would never detect a double spend TX with Neutrino (this was found through a unit test in lnd: https://github.com/lightningnetwork/lnd/pull/6285#issuecomment-1047332223)
Not sure if this proposed solution is any better, I'm definitely open for suggestions as I'm not too familiar with this code base.
> Fix TX reject messages not being counted anymore

- pushtx/broadcaster.go
- pushtx/broadcaster_test.go
Relates to lightningnetwork/lnd#7156.
~~Looking for a Concept ACK here.~~
This makes sure our rebroadcaster continues broadcasting transactions when they are for example rejected because the `min mempool fee` is not met. ~~It becomes a bit messy to now include some other backend conversions into the `pushtx` package which is mainly a neutrino package? So the most cleanest way would be to maybe reimplement the rebroadcaster for the different backends?~~
~~This solution gets the job done, so open for suggestions.~~
> pushtx: map different backend err to internal err.

- headerfs/store.go
Improve error messages for header store regards the write and chain tip operations. This would be useful in debugging for example when the user has corrupt headers data.
Follow-up on #313.
> headerfs: improve error messages for header store

- .golangci.yml
- tools/Dockerfile
Add new Linter line width restriction from now on.
> linter: add 80 column restriction
